const BUNDLE_CMD = 'bundle';
const BUNDLE_OUTPUT_CLI_ARG = '--bundle-output';
const BUNDLE_SOURCEMAP_OUTPUT_CLI_ARG = '--sourcemap-output';
const BUNDLE_DEV_CLI_ARG = '--dev';
const TEMP_FOLDER = '.jso';
const DIST_TEMP_FOLDER = `${TEMP_FOLDER}/dist`;
const SOURCE_MAPS_TEMP_FOLDER = `${DIST_TEMP_FOLDER}/jsoSourceMaps`;
const SRC_TEMP_FOLDER = `${TEMP_FOLDER}/src`;
const BEG_ANNOTATION = '"JSO-BEG";';
const END_ANNOTATION = '"JSO-END";';
const EXTS = /.(j|t)s(x)?$/i;

module.exports = {
  BUNDLE_CMD,
  BUNDLE_OUTPUT_CLI_ARG,
  BUNDLE_SOURCEMAP_OUTPUT_CLI_ARG,
  BUNDLE_DEV_CLI_ARG,
  TEMP_FOLDER,
  DIST_TEMP_FOLDER,
  SOURCE_MAPS_TEMP_FOLDER,
  SRC_TEMP_FOLDER,
  BEG_ANNOTATION,
  END_ANNOTATION,
  EXTS
}
